### PR TITLE
Created a WPF application for the UI and an engine for the homebrew listing, downloading etc.

### PR DESCRIPTION
**Pull request by fthdgn-gh**
First of all, great project, keep up the good work.
Second of all, sorry for the huge commit, I should have done better about that.
With this PR, I actually wanted to improve this project and maybe hopefully improve your coding style.
Please don't get me wrong, I'm doing this with good intentions and nothing more.
Hope to see you get better with your craft :)

### CODE REVIEW

**Comment by MRGhidini** [comment]
Nice.
Thank you

**Comment by fthdgn-gh** [comment]
Well, thanks for the merge 👍 I guess now I can update the readme file with new descriptions and new screenshots. It also means there would be a new release too. Could we arrange that with you on this repo or would I have to make those changes and create a new PR?

**Comment by MRGhidini** [comment]
We can continue here, as soon as I get home I'm going to compile and test, can we talk on twitter or other means of communication? ?

**Comment by fthdgn-gh** [comment]
I don't have a twitter but we can talk through mail. My mail address is fth.dgn.369@gmail.com. From there we can switch to something else if you want.

**Pull request merged**
